insert into USERS (email, name, password, phone, address, regdate, token, active) values ('info1@csabszak.com', 'Gyula', '11111', '0690444555676', 'Balatonfüred', '2016-1-9', 52301, TRUE)
insert into USERS (email, name, password, phone, address, regdate, token, active) values ('info2@csabszak.com', 'Géza', '11111', '069053595023', 'Paks', '2017-12-25', 33216, TRUE)
insert into USERS (email, name, password, phone, address, regdate, token, active) values ('info3@csabszak.com', 'Béla', '11111', '069054565464', 'Dunaújváros', '2018-5-5', 45622, TRUE)
insert into USERS (email, name, password, phone, address, regdate, token, active) values ('info4@csabszak.com', 'Lajos', '11111', '0690535567657', 'Kiskunlacháza', '2018-7-9', 61677, TRUE)
insert into USERS (email, name, password, phone, address, regdate, token, active) values ('admin@csabszak.com', 'SuperAdmin', 'pass', '0690535565555', 'Budapest', '2018-7-9', 61677, TRUE)
insert into USERS (email, name, password, phone, address, regdate, token, active) values ('workmate1@csabszak.com', 'Batman', 'pass', '0690535565555', 'Budapest', '2018-7-9', 61677, TRUE)
insert into USERS (email, name, password, phone, address, regdate, token, active) values ('workmate2@csabszak.com', 'Superman', 'pass', '0690535565666', 'Budapest', '2018-7-9', 61677, TRUE)

insert into ROLES (role) values ('USER')
insert into ROLES (role) values ('EDITOR')
insert into ROLES (role) values ('ADMIN')

insert into users_roles (user_id, role_id) values ('admin@csabszak.com',3)
insert into users_roles (user_id, role_id) values ('info1@csabszak.com',1)
insert into users_roles (user_id, role_id) values ('info2@csabszak.com',1)
insert into users_roles (user_id, role_id) values ('info3@csabszak.com',1)
insert into users_roles (user_id, role_id) values ('info4@csabszak.com',1)
insert into users_roles (user_id, role_id) values ('workmate1@csabszak.com',2)
insert into users_roles (user_id, role_id) values ('workmate2@csabszak.com',2)
insert into users_roles (user_id, role_id) values ('workmate2@csabszak.com',3)

insert into TICKETS (task, startdate, client_email) values ('Nincs internet kapcsolat a számítógépen! SOS!', '2017-10-6', (select email from USERS where email='info1@csabszak.com'))
insert into TICKETS (task, startdate, client_email) values ('Központi szerver nem indul. Sürgős!', '2018-5-11', (select email from USERS where email='info2@csabszak.com'))
insert into TICKETS (task, startdate, client_email) values ('VLC média player nem indul. ', '2018-8-19', (select email from USERS where email='info3@csabszak.com'))
insert into TICKETS (task, startdate, client_email) values ('Új nyomtató üzembe helyezése.', '2018-10-9', (select email from USERS where email='info4@csabszak.com'))
insert into TICKETS (task, startdate, client_email) values ('Árajánlat kérése weboldal készítésére.', '2018-10-20', (select email from USERS where email='info1@csabszak.com'))
insert into TICKETS (task, startdate, client_email) values ('Számítógép kékhalálozik.', '2018-10-25', (select email from USERS where email='info1@csabszak.com'))
insert into TICKETS (task, startdate, client_email) values ('Levelező rendszer nem megy.', '2018-10-29', (select email from USERS where email='info2@csabszak.com'))
insert into TICKETS (task, startdate, client_email) values ('Facebook lassú.', '2018-10-11', (select email from USERS where email='info4@csabszak.com'))
insert into TICKETS (task, startdate, client_email) values ('3 monitor cseréje.', '2018-9-30', (select email from USERS where email='info1@csabszak.com'))
