insert into BLOGGER (name, age) values ('Csaba', 21)
insert into STORIES (content, posted, title, blogger_id) values ('Ez egy sztori. Már rég átírtam a szöveget!!!', '2018-10-6', 'Az emberi lelek', (select id from blogger where name='Csaba'))

insert into USERS (name, password, phone, address, regdate, token, active, role) values ('Hans Solo', '54321', '0690444555676', 'Corellia', '2016-1-9', 52301, TRUE, 'USER')
insert into USERS (name, password, phone, address, regdate, token, active, role) values ('Padmé Amidala', '34356', '069053595023', 'Naboo, Theed', '2017-12-25', 33216, TRUE, 'USER')
insert into USERS (name, password, phone, address, regdate, token, active, role) values ('Luke Skywalker', '16542', '069054565464', 'Tatooine', '2018-5-5', 45622, TRUE, 'USER')
insert into USERS (name, password, phone, address, regdate, token, active, role) values ('Yoda', '78776', '0690535567657', 'Dagobah', '2018-7-9', 61677, TRUE, 'USER')

insert into TICKETS (content, date, user_id) values ('Nincs internet kapcsolat a számítógépen! SOS!', '2017-10-6', (select id from USERS where name='Hans Solo'))
insert into TICKETS (content, date, user_id) values ('Központi szerver nem indul. Sürgős!', '2018-5-11', (select id from USERS where name='Padmé Amidala'))
insert into TICKETS (content, date, user_id) values ('VLC média player nem indul. ', '2018-8-19', (select id from USERS where name='Yoda'))
insert into TICKETS (content, date, user_id) values ('Nem indul az Ezerévessólyom.', '2018-9-14', (select id from USERS where name='Hans Solo'))
insert into TICKETS (content, date, user_id) values ('R2D2 megbolondult.', '2018-9-30', (select id from USERS where name='Hans Solo'))
insert into TICKETS (content, date, user_id) values ('Fénykard magától kikapcsol.', '2018-10-1', (select id from USERS where name='Luke Skywalker'))
insert into TICKETS (content, date, user_id) values ('Vállalati Skype nem megy a Halálcsillagon.', '2018-10-10', (select id from USERS where name='Luke Skywalker'))
insert into TICKETS (content, date, user_id) values ('3PO nyikorog.', '2018-10-13', (select id from USERS where name='Padmé Amidala'))
insert into TICKETS (content, date, user_id) values ('X-szárnyú tömeges költöztetés.', '2018-10-14', (select id from USERS where name='Luke Skywalker'))
insert into TICKETS (content, date, user_id) values ('Lézerpisztoly nem mindig működik.', '2017-10-6', (select id from USERS where name='Hans Solo'))
insert into TICKETS (content, date, user_id) values ('Nincs WiFi.', '2018-5-11', (select id from USERS where name='Padmé Amidala'))
insert into TICKETS (content, date, user_id) values ('Új igény: új fénykard.', '2018-9-10', (select id from USERS where name='Yoda'))
insert into TICKETS (content, date, user_id) values ('Ezerévessólyom monitor SKSH.', '2018-9-14', (select id from USERS where name='Hans Solo'))
insert into TICKETS (content, date, user_id) values ('R2D2 megbolondult.', '2018-9-16', (select id from USERS where name='Hans Solo'))
insert into TICKETS (content, date, user_id) values ('Jedi erő hamar lemerül. Akksi?', '2018-9-18', (select id from USERS where name='Luke Skywalker'))
insert into TICKETS (content, date, user_id) values ('Halálsugár gyenge.', '2018-10-10', (select id from USERS where name='Luke Skywalker'))
insert into TICKETS (content, date, user_id) values ('3PO firmware update szükséges.', '2018-10-13', (select id from USERS where name='Padmé Amidala'))
insert into TICKETS (content, date, user_id) values ('Birodalmi lépegető lassú.', '2018-10-14', (select id from USERS where name='Luke Skywalker'))